### ISSUE TITLE
Cannot add to area

### ISSUE THREAD

**Issue by pkaak** [dr1rrb/ha-twinkly#2]
it seems it is not possible to edit the entitity so it can be set to an area.
(I have multiple Twinkly devices in the configuration).

Would be nice to be able to set it to an area.

**Comment by dr1rrb** [comment]
FYI I tried to have a look at this, but unfortunately I was not able to determine what is the requirement for HA to allow us to add the entity to an area.

I'm planning to add a configuration flow to be able to add devices from the UI. This would allow me to have a unique ID (which is required by HA to allow basic setup of devices like overriding the icon and the name). I'm hoping this would also let us assign devices to areas.

**Comment by dr1rrb** [comment]
Good! I was finally able to find the doc https://developers.home-assistant.io/docs/device_registry_index/#defining-devices and implemented it successfully :

![image](https://user-images.githubusercontent.com/8635919/95856248-b8307080-0d27-11eb-8124-840bec585fe8.png)

But as expected it requires to setup the entity using the "config_flow" (i.e. setup from the UI, not configuration.yaml). So it won't be available until my component is merged in HA.

**Comment by dr1rrb** [comment]
@pkaak : Great news, my integration has been merged in Home-Assistant (https://github.com/home-assistant/core/pull/42103) and should be available starting from 0.119 which is planned on 13/12/2020. Once you have reconfigured your devices using the core integration (remove them from your `configuration.yaml` and add them back using the UI), you will be able to add you device to an area/room.
