### ISSUE TITLE
Throws some error in the log!

### ISSUE THREAD

**Issue by 24hourbullshit** [dr1rrb/ha-twinkly#3]
2020-08-28 14:39:42 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify TwinklyLight to extend LightEntity

I guess it's a easy fix!

**Comment by dr1rrb** [comment]
Yeah I saw this appear last week, I'll try to tackle it soon. Thanks for the report 👍

**Comment by B-Hartley** [comment]
Any news on this update. 
I’m worried that at some point it will
stop working when light is deprecated. 

Thanks very much. 
A great component.

**Comment by dr1rrb** [comment]
Great news, I had time to create a new Home-Assistant dev environment and updated to the `LightEntity` (It was indeed a really easy fix 🙂 ) It's already available, you just have to update.

**Comment by 24hourbullshit** [comment]
Great news, no more errors, thanks for your work on implementing Twinkly to HA :)
