### ISSUE TITLE
api douments

### ISSUE THREAD

**Issue by matteos1** [dr1rrb/ha-twinkly#4]
I read on the net that there are rest-api that cnsentoo the total implementation of the device for third-party use. did you take a look?
(https://xled-docs.readthedocs.io/en/latest/rest_api.html)

**Comment by dr1rrb** [comment]
Yeah I found it, but a but too late. I'm planning to remove my client and use 'xled' instead.

Closing this issue in favor of https://github.com/dr1rrb/ha-twinkly/issues/5
