### ISSUE TITLE
Twinkly in Device List for Automation

### ISSUE THREAD

**Issue by mgoetting** [dr1rrb/ha-twinkly#7]
I am using this integration successfully for a while.

My Twinkly Fesstoons can be witched on/off and control brightness via light card in HA.

The Entity I call is light.twinkly, this works perfectly!!!

Now as my wife always forgets to switch Twinkly off in the morning I want to Add an Automation for this to switch it off at sunrise.

All Hue lights I have the automation of this is at no issue but Twinkly is not listed at all under devices.

Is there any suggestion how an automation for twinkly off at sunrise can be created, am I overlooking something, or is there a bug that could be fixed.

Thx in advance!

**Comment by TheFuzz4** [comment]
You can do this via nodered or even the built in automation section within HomeAssistant very easy.  Just set a condition for when sun.sun is above horizon and have it execute and turn off the lights.  I do mine all via appdaemon but same thing.

**Comment by dr1rrb** [comment]
@mgoetting Indeed, the Twinkly are not listed as a device as we cannot declare a "device" from HACS / custom_integration (We can declare only "entities" ... well at least when I did this component). Those kind of limitations are the main reason why I moved to a real integration in HA (https://github.com/home-assistant/core/pull/42103).

Starting from 0.119 you will see them in the device list (you will have to remove current config and re-add you twinkly devices using the UI), but for now in the HA automations you can just call the `light.turn_<on|off>` service:

![image](https://user-images.githubusercontent.com/8635919/100530741-9bf76e80-31c3-11eb-8eaf-c32dd216fb94.png)
